name: Hello-World_workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: |
          python square.py
  
