name: Hello-World_workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: |
          python square.py
  
