name: workflow2
on:
  workflow_dispatch:
    inputs:
      A:
        description: 1stinteger
        required: true
        type: number
      B:
        description: 2ndiinteger
        required: true
        type: number
jobs:
  call_sum_workflow:
    # runs-on: ubuntu-latest
    # steps:
    #   - name: print pwd
    #     run: |
    #       echo pwd
    #   - name: Checkout Repo
    #     uses: actions/checkout@v4
    #   - name: uses sum workflow
      uses: ./.github/workflows/sum.yml
      with: |
        A: ${{ github.event.inputs.A }}
        B: ${{ github.event.inputs.B }}
      
